name: madathil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  hive: ^2.2.3
  path_provider: ^2.1.4
  flutter_svg: ^2.0.10+1

  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/
